### ISSUE TITLE
Configure SonarCloud to ignore our test code

### ISSUE THREAD

**Issue by drdavella** [pixee/codemodder-python#271]
Sonar gets pretty upset about some of our test code. Probably because many of these tests have examples that are deliberately intended to trigger Sonar rules 😅 

We need to make sure that test code is ignored by Sonar. This includes
* `tests/samples`
* `integration_tests`
* Maybe others?

**Comment by clavedeluna** [comment]
I'm surprised to not see a way to configure this on the sonarcloud UI. @drdavella do I by chance not have full permissions there? Are you able to see some settings about exclusions? You appear as an admin.

> Note that some of these settings can also be configured from the SonarCloud UI. In your project’s Administration > General Settings > Analysis Scope > Files, you can define file exclusions and inclusions. If you have different options set on the UI and the .sonarcloud.properties file, SonarCloud will only take into account the one from the .sonarcloud.properties file.

**Comment by drdavella** [comment]
@clavedeluna I _think_ this is done by means of this file: https://github.com/pixee/codemodder-python/blob/main/sonar-project.properties. But I'm not entirely convinced that it's working. If it is working, we can close this issue.

**Comment by clavedeluna** [comment]
Given the failures [in the main branch](https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&id=pixee_codemodder-python) I think we can say it isn't working. I'll take a look.

**Comment by clavedeluna** [comment]
I've created an i[issue for the sonar team](https://community.sonarsource.com/t/setting-sonar-exclusions-in-sonar-project-propert-does-not-exclude-files-in-sonarcloud/110539) because nothing I do makes this work.
