### ISSUE TITLE
Codemod to add a `__str__` method to a Django model that didn't define it

### ISSUE THREAD

**Issue by clavedeluna** [pixee/codemodder-python#287]
Django users write lots of models and may forget that not defining a `__str__` will make the model really hard to read in admin tools.
It would be good to change this model
```
from django.db import models

class User(models.Model):
    name = models.CharField(max_length=100)

   .... 
```
To include:
```
    def __str__(self):
        return f'{self.name}'
```

The challenges I see to this is to decide what should `__str__` return? Which fields should we include? Is something like this acceptable?
```
    def __str__(self):
        return f'{field for field in all_defined_fields}'
```

**Comment by clavedeluna** [comment]
There is also a sonar rule that we can add for support https://rules.sonarsource.com/python/RSPEC-6554/

**Comment by clavedeluna** [comment]
@andrecsilva @drdavella I'd love your opinions on what you think the replacement code should be. The goal is to add a meaningful `__str__` method.

1. easy, have users come back and update the code
```
    def __str__(self):
        return "Please implement __str__" # maybe even add filename
```

2. a bit harder:  we need to detect each field and print each. This could really get unwieldy if there are lots of fields 
```
    def __str__(self):
       return f"\
            name: {self.name}\n
            phone: {self.phone}\n
            # etc for each field
            "
```

3. Some version of 1 or 2 (such as printing self.pk or a couple of fields only), or something else?

**Comment by andrecsilva** [comment]
> @andrecsilva @drdavella I'd love your opinions on what you think the replacement code should be. The goal is to add a meaningful `__str__` method.
> 
>     1. easy, have users come back and update the code
> 
> 
> ```
>     def __str__(self):
>         return "Please implement __str__" # maybe even add filename
> ```
> 
>     2. a bit harder:  we need to detect each field and print each. This could really get unwieldy if there are lots of fields
> 
> 
> ```
>     def __str__(self):
>        return f"\
>             name: {self.name}\n
>             phone: {self.phone}\n
>             # etc for each field
>             "
> ```
> 
>     3. Some version of 1 or 2 (such as printing self.pk or a couple of fields only), or something else?

My understanding is that Django models are product types/cartesian product of its fields. So a tuple representation is appropriate.

Thus, something like:
```python
f"{self.__class__.__name__}(field1 = {self.field1}, field2 = {self.field2}, ...)"
```
Using the `User` defined above as an example:
```
User(name=Alice)
```

**Comment by clavedeluna** [comment]
> ```
> User(name=Alice)
> ```

I like it. It's reasonable, although it doesn't address the issue of too many fields. The goal of writing a __str__ is that when you query a django model (or use admin tools) the model doesn't show up as `<QuerySet [<User:>,<User:>..]`. So for models with only a few fields doing `<QuerySet [User(name=Alice, phone=12345), User(name=Bob, phone=53234)..]` isn't overwhelming. But django models that have dozens of fields will become overwhelming to read, thus forcing users to revisit the return value of `__str__` anyway.

I'll take this route for now and if we want to change it later, we can.
