### ISSUE TITLE
Codemod for deprecated `@abstractclassmethod` and `@abstractstaticmethod`

### ISSUE THREAD

**Issue by drdavella** [pixee/codemodder-python#312]
We currently have a codemod to replace deprecated `@abstractproperty`. Ideally we should add deprecated `@abstractclassmethod` to this as well, although it won't be reflected by the current name of the codemod.

**Comment by clavedeluna** [comment]
This is a great example for thinking about what how we want to handle the name of the codemod if its scope changes. Right now we could leave the same name, we could also decide to change the name right now if we think not many have started to use this codemod's id and if it won't be an issue with our docs. As a long-term solution, we'll want to come up with a way to document renamed codemods. Here's [one example](https://pylint.readthedocs.io/en/stable/user_guide/messages/fatal/old-import-error.html) for how we could do it.

**Comment by drdavella** [comment]
I agree that having some kind of deprecation/renaming strategy would be good. In this particular case I think the scope is similar enough that we can just keep the same name for now.
