### ISSUE TITLE
Use Pydantic for CodeTF data models

### ISSUE THREAD

**Issue by drdavella** [pixee/codemodder-python#340]
Pydantic enables automatic validation of data models: https://docs.pydantic.dev/latest/

We should use Pydantic to define our CodeTF data structures to enable automatic serialization and validation.

**Comment by hamzasial1911** [comment]
can you assign this ticket to me? @drdavella

**Comment by drdavella** [comment]
Hi @hamzasial1911 thanks for your interest in contributing! This work is already in progress but if you'd like to choose another issue please let me know.

**Comment by drdavella** [comment]
Closed by #357.
