### ISSUE TITLE
Sonar codemod: Fix datetime.utc

### ISSUE THREAD

**Issue by drdavella** [pixee/codemodder-python#368]
https://rules.sonarsource.com/python/RSPEC-6714

**Comment by clavedeluna** [comment]
@drdavella  is this the correct sonar rule? https://rules.sonarsource.com/python/RSPEC-6903/

**Comment by drdavella** [comment]
Ah yes, sorry I must have pasted the wrong link.

**Comment by clavedeluna** [comment]
closing to combine issues
