### ISSUE TITLE
Sonar codemod: fix "Floating point numbers should not be tested for equality"

### ISSUE THREAD

**Issue by drdavella** [pixee/codemodder-python#374]
https://rules.sonarsource.com/python/type/Bug/RSPEC-1244/

**Comment by drdavella** [comment]
We should implement find + fix for this as well.

**Comment by clavedeluna** [comment]
@drdavella I'm wondering if this would be better as an LLM codemod, specifically because of the values for rel_tol and abs_tol. Take a look at the sonar change
original:
```
def foo(a, b):
    return a == b - 0.1
```
update
```
import math
def foo(a, b):
    return math.isclose(a, b - 0.1, rel_tol=1e-09, abs_tol=1e-09)
```

we could just use the default values of rel_tol and abs_tol, but either that or picking a value arbitrarily may fail the code. Instead, a user should really think about what values are acceptable for these args for their code.

As another option, this could be a codemod that accepts params.
What do you think?

**Comment by drdavella** [comment]
@clavedeluna that's a good point. I think this falls in a similar category of our requests timeout where we pick a fairly arbitrary but reasonable value and add some text to the description that indicates the user might want to adjust before merging. Would it seem reasonable to do the same here? Eventually it would be good to add some more intelligent logic for picking params, but honestly I'm not sure if an LLM would be all that helpful in this particular case 🤔

**Comment by clavedeluna** [comment]
@drdavella yeah it's true LLMs are known to not be strong at math, and in this case a good pick for the kwargs would take into account the calculation itself, unlike the request timeout, which picks a timeout value that's going to be good for pretty much all websites for timeout. But for this case:
```
import math
def foo(a, b):
    return math.isclose(a, b - 0.1, rel_tol=1e-09, abs_tol=1e-09) # abs_tol must be a copy-paste error
```
the values of rel and abs tolerance a user may want to pick very much would depend on what they believe the values of `a` and `b` are going to be.

I think if we want to go ahead with this codemod, the smartest choice would be to explicitly use the default values `rel_tol=1e-09, abs_tol=0.0)`   [explained here](https://docs.python.org/3/library/math.html#math.isclose) but as you said in the docs explain users should think about if those values are good

**Comment by drdavella** [comment]
I'm good with just relying on the defaults. We can wait for feedback if that's an unreasonable change.
