### ISSUE TITLE
Sonar: fix using PNRGs with `secure-random`

### ISSUE THREAD

**Issue by drdavella** [pixee/codemodder-python#376]
https://rules.sonarsource.com/python/type/Security%20Hotspot/RSPEC-2245/

**Comment by clavedeluna** [comment]
As I started working on supporting this, I discovered this results in sonar "hotspots", not "issues", which codemodder currently does not support. We will hold off until the platform team moves forward with some research.

I will leave [this branch](https://github.com/pixee/codemodder-python/commits/secure-sonar/) which has my work with useful testing.
