### ISSUE TITLE
`fix-missing-self-or-cls` is missing `self.node_is_selected` check

### ISSUE THREAD

**Issue by clavedeluna** [pixee/codemodder-python#413]
All codemods should have logic similar to `self.node_is_selected` to check if results exist for this codemod. When writing this codemod we forgot to update sonar_issues.json which made the integration test for this codemod pass. However, adding the `self.node_is_selected` would've alerted us to having forgotten to add a corresponding sonar issue.

**Comment by drdavella** [comment]
I'm curious whether this failure is related: https://github.com/pixee/codemodder-python/actions/runs/8420800708/job/23056254528
