### ISSUE TITLE
Parser and transformation failures should also update unfixed findings

### ISSUE THREAD

**Issue by drdavella** [pixee/codemodder-python#514]
For codemods that fix tool results, if we fail to parse or transform a particular file, we should also update the unfixed findings in CodeTF to reflect the fact that we won't be able to fix findings for that codemod in that file.

**Comment by clavedeluna** [comment]
For this to work, all tools need the `finding` field populated. Right now only defectdojo has it populated.  @drdavella what's the priority to add that?

**Comment by drdavella** [comment]
@clavedeluna I think it's reasonably important to do this for Sonar codemods. However I also think we should implement this in such a way that it's tolerant of codemods that do not have findings.
