### ISSUE TITLE
Add dependencies to projects that are using `poetry`

### ISSUE THREAD

**Issue by drdavella** [pixee/codemodder-python#634]
For codemods that add dependencies, we should add support for `poetry`. It looks like dependencies are generally expressed in `pyproject.toml` under `[tool.poetry.dependencies]` although it also appears possible to include subgroups: https://python-poetry.org/docs/managing-dependencies/

It should be fairly simple to extend our existing dependency manager for `pyproject.toml` to also consider `poetry`.

We can limit scope here by saying that we will _not_ update lock files. It will be incumbent upon the user to do this themselves, although we anticipate providing a GitHub action that can do it automatically.

**Comment by clavedeluna** [comment]
@drdavella this is hopefully rare but one edge case I thought of is dependencies are declared both in [project]/ dependencies AND  under [tool.poetry.dependencies], like this
```

    [build-system]
    requires = ["setuptools"]
    build-backend = "setuptools.build_meta"

    [project]
    name = "pkg for testing"
    version = "0.60.0"
    requires-python = ">=3.10.0"
    readme = "README.md"
    license = {file = "LICENSE"}
    dependencies = [
        "isort~=5.12.0"
       ]

    [tool.poetry.dependencies]
    python = "^3.11"
    numpy = "^1.24.4"
    astropy = "^5.2.2"
```

In this case, I can imagine this behavior:
1. `PyprojectTomlParser` should be able to parse both and store all dependencies for the codemodder run
2. if a codemod needs to add a dependency, `PyprojectWriter` should give priority to adding it under `    [tool.poetry.dependencies]` if it exists.

Is this the behavior you'd expect, or do we want to do something else?

**Comment by drdavella** [comment]
@clavedeluna yes in the absence of any additional feedback I think that sounds sensible. I do think it makes sense for `poetry` to take priority if present.
