### ISSUE TITLE
Deprecate CodemodRegistry _codemods_by_name and codemod names in general

### ISSUE THREAD

**Issue by clavedeluna** [pixee/codemodder-python#697]
When we had few codemods, having both codemod name and id made sense, but now that we use the same transformer for various SAST tools, calling a codemod by a name and not by an id doesn't disambiguate. To prevent future confusion, we should go ahead and deprecate codemod names and storing them in the registry. Only codemod ids should be used to invoke codemods

This may mean we still retain the `name`field for the codemod metadata, but only as a simplified way to instantiate a codemod. It can only ever be accessed by it's full id, specifying tool provider.

**Comment by clavedeluna** [comment]
@drdavella I just want to point out that this will likely mean it's time for a new codemodder major version. Are we ready for 1.0?

**Comment by drdavella** [comment]
@clavedeluna yes I've been looking for an excuse to bump it anyway 😅
