### ISSUE TITLE
use walrus assignment codemod needs handle edge case differently

### ISSUE THREAD

**Issue by clavedeluna** [pixee/codemodder-python#728]
```
successes = [False, True]
 all_success = False not in success
 if not all_success:
       ...
```
this codemod currently makes this change
```
-    if not all_success:
+    if not False not in success:
```

which is not equivalent.

we could:
1. add parenthesis
2. remove the first not

**Comment by drdavella** [comment]
@clavedeluna is this the same as #650?

**Comment by clavedeluna** [comment]
@drdavella I was going crazy as to why when I made the issue it makes sense but yours somehow didn't logically. I figured out why!

your replacement snipped
```
if not False in list_of_bools:
    do_something()
``` 
is logically correct and equal to the original.

However the one in this issue
`if not False not in success:` 

absolutely is just wrong. the difference is the second `not`. So I think this is the right one we want to fix but also add the other one as a unit test and decide if that merits perens or not.

**Comment by clavedeluna** [comment]
I have come full circle in my confusion on this. I think there is nothing to do here. I was mistaken in that the replacement logic was wrong.

```
>>> successes = [False, True]
>>> all_success = False not in successes
>>> if not all_success:
...     print("at least one False")
...
at least one False
>>> if not False not in successes:
...     print("at least one False")
...
at least one False
>>> if not False in successes:
...     print("no False in list")
...
```
